server:
  port: 4005
spring:
  mail:
    host: smtp.163.com
    username: javatestyukiice@163.com
    password: IXQADHCOAZKVCVTX
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=t rue&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456789
  redis:
    host: 49.235.70.200
    port: 6379
    password: yukiice123
    database: 0
mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /Users/yukiice/Documents/upload/reggie/